kind = "mobile"
previewPath = "/"
title = "Anime App"
version = "1.0.0"
id = "artifacts/anime-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19020

[services.development]
run = "pnpm --filter @workspace/anime-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/anime-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/anime-app", "run", "serve" ]

[services.env]
PORT = "19020"
BASE_PATH = "/"
